export let attackers = [
  {
    id: 1,
    name: "Sledge",
    image: "../assets/images/sledge.png",
    icon: "../assets/icons/sledge-icon.png",
    active: true,
  },
  {
    id: 2,
    name: "Thatcher",
    image: "../assets/images/thatcher.png",
    icon: "../assets/icons/thatcher-icon.png",
    active: true,
  },
  {
    id: 3,
    name: "Ash",
    image: "../assets/images/ash.png",
    icon: "../assets/icons/ash-icon.png",
    active: true,
  },
  {
    id: 4,
    name: "Thermite",
    image: "../assets/images/thermite.png",
    icon: "../assets/icons/thermite-icon.png",
    active: true,
  },
  {
    id: 5,
    name: "Twitch",
    image: "../assets/images/twitch.png",
    icon: "../assets/icons/twitch-icon.png",
    active: true,
  },
  {
    id: 6,
    name: "Montagne",
    image: "../assets/images/montagne.png",
    icon: "../assets/icons/montagne-icon.png",
    active: true,
  },
  {
    id: 7,
    name: "Glaz",
    image: "../assets/images/glaz.png",
    icon: "../assets/icons/glaz-icon.png",
    active: true,
  },
  {
    id: 8,
    name: "Fuze",
    image: "../assets/images/fuze.png",
    icon: "../assets/icons/fuze-icon.png",
    active: true,
  },
  {
    id: 9,
    name: "Blitz",
    image: "../assets/images/blitz.png",
    icon: "../assets/icons/blitz-icon.png",
    active: true,
  },
  {
    id: 10,
    name: "IQ",
    image: "../assets/images/iq.png",
    icon: "../assets/icons/iq-icon.png",
    active: true,
  },
  {
    id: 11,
    name: "Buck",
    image: "../assets/images/buck.png",
    icon: "../assets/icons/buck-icon.png",
    active: true,
  },
  {
    id: 12,
    name: "Blackbeard",
    image: "../assets/images/blackbeard.png",
    icon: "../assets/icons/blackbeard-icon.png",
    active: true,
  },
  {
    id: 13,
    name: "Capitão",
    image: "../assets/images/capitão.png",
    icon: "../assets/icons/capitão-icon.png",
    active: true,
  },
  {
    id: 14,
    name: "Hibana",
    image: "../assets/images/hibana.png",
    icon: "../assets/icons/hibana-icon.png",
    active: true,
  },
  {
    id: 15,
    name: "Jackal",
    image: "../assets/images/jackal.png",
    icon: "../assets/icons/jackal-icon.png",
    active: true,
  },
  {
    id: 16,
    name: "Ying",
    image: "../assets/images/ying.png",
    icon: "../assets/icons/ying-icon.png",
    active: true,
  },
  {
    id: 17,
    name: "Zofia",
    image: "../assets/images/zofia.png",
    icon: "../assets/icons/zofia-icon.png",
    active: true,
  },
  {
    id: 18,
    name: "Dokkaebi",
    image: "../assets/images/dokkaebi.png",
    icon: "../assets/icons/dokkaebi-icon.png",
    active: true,
  },
  {
    id: 19,
    name: "Lion",
    image: "../assets/images/lion.png",
    icon: "../assets/icons/lion-icon.png",
    active: true,
  },
  {
    id: 20,
    name: "Finka",
    image: "../assets/images/finka.png",
    icon: "../assets/icons/finka-icon.png",
    active: true,
  },
  {
    id: 21,
    name: "Maverick",
    image: "../assets/images/maverick.png",
    icon: "../assets/icons/maverick-icon.png",
    active: true,
  },
  {
    id: 22,
    name: "Nomad",
    image: "../assets/images/nomad.png",
    icon: "../assets/icons/nomad-icon.png",
    active: true,
  },
  {
    id: 23,
    name: "Gridlock",
    image: "../assets/images/gridlock.png",
    icon: "../assets/icons/gridlock-icon.png",
    active: true,
  },
  {
    id: 24,
    name: "Nøkk",
    image: "../assets/images/nøkk.png",
    icon: "../assets/icons/nøkk-icon.png",
    active: true,
  },
  {
    id: 25,
    name: "Amaru",
    image: "../assets/images/amaru.png",
    icon: "../assets/icons/amaru-icon.png",
    active: true,
  },
  {
    id: 26,
    name: "Kali",
    image: "../assets/images/kali.png",
    icon: "../assets/icons/kali-icon.png",
    active: true,
  },
  {
    id: 27,
    name: "Iana",
    image: "../assets/images/iana.png",
    icon: "../assets/icons/iana-icon.png",
    active: true,
  },
  {
    id: 28,
    name: "Ace",
    image: "../assets/images/ace.png",
    icon: "../assets/icons/ace-icon.png",
    active: true,
  },
  {
    id: 29,
    name: "Zero",
    image: "../assets/images/zero.png",
    icon: "../assets/icons/zero-icon.png",
    active: true,
  },
  {
    id: 30,
    name: "Flores",
    image: "../assets/images/flores.png",
    icon: "../assets/icons/flores-icon.png",
    active: true,
  },
  {
    id: 31,
    name: "Osa",
    image: "../assets/images/osa.png",
    icon: "../assets/icons/osa-icon.png",
    active: true,
  },
  {
    id: 32,
    name: "Sens",
    image: "../assets/images/sens.png",
    icon: "../assets/icons/sens-icon.png",
    active: true,
  },
  {
    id: 33,
    name: "Grim",
    image: "../assets/images/grim.png",
    icon: "../assets/icons/grim-icon.png",
    active: true,
  },
  {
    id: 34,
    name: "Brava",
    image: "../assets/images/brava.png",
    icon: "../assets/icons/brava-icon.png",
    active: true,
  },
  {
    id: 35,
    name: "Ram",
    image: "../assets/images/ram.png",
    icon: "../assets/icons/ram-icon.png",
    active: true,
  },
  {
    id: 36,
    name: "Deimos",
    image: "../assets/images/deimos.png",
    icon: "../assets/icons/deimos-icon.png",
    active: true,
  }
];

export let defenders = [
  {
    id: 1,
    name: "Smoke",
    image: "../assets/images/smoke.png",
    icon: "../assets/icons/smoke-icon.png",
    active: true,
  },
  {
    id: 2,
    name: "Mute",
    image: "../assets/images/mute.png",
    icon: "../assets/icons/mute-icon.png",
    active: true,
  },
  {
    id: 3,
    name: "Castle",
    image: "../assets/images/castle.png",
    icon: "../assets/icons/castle-icon.png",
    active: true,
  },
  {
    id: 4,
    name: "Pulse",
    image: "../assets/images/pulse.png",
    icon: "../assets/icons/pulse-icon.png",
    active: true,
  },
  {
    id: 5,
    name: "Doc",
    image: "../assets/images/doc.png",
    icon: "../assets/icons/doc-icon.png",
    active: true,
  },
  {
    id: 6,
    name: "Rook",
    image: "../assets/images/rook.png",
    icon: "../assets/icons/rook-icon.png",
    active: true,
  },
  {
    id: 7,
    name: "Kapkan",
    image: "../assets/images/kapkan.png",
    icon: "../assets/icons/kapkan-icon.png",
    active: true,
  },
  {
    id: 8,
    name: "Tachanka",
    image: "../assets/images/tachanka.png",
    icon: "../assets/icons/tachanka-icon.png",
    active: true,
  },
  {
    id: 9,
    name: "Jäger",
    image: "../assets/images/jäger.png",
    icon: "../assets/icons/jäger-icon.png",
    active: true,
  },
  {
    id: 10,
    name: "Bandit",
    image: "../assets/images/bandit.png",
    icon: "../assets/icons/bandit-icon.png",
    active: true,
  },
  {
    id: 11,
    name: "Frost",
    image: "../assets/images/frost.png",
    icon: "../assets/icons/frost-icon.png",
    active: true,
  },
  {
    id: 12,
    name: "Valkyrie",
    image: "../assets/images/valkyrie.png",
    icon: "../assets/icons/valkyrie-icon.png",
    active: true,
  },
  {
    id: 13,
    name: "Caveira",
    image: "../assets/images/caveira.png",
    icon: "../assets/icons/caveira-icon.png",
    active: true,
  },
  {
    id: 14,
    name: "Echo",
    image: "../assets/images/echo.png",
    icon: "../assets/icons/echo-icon.png",
    active: true,
  },
  {
    id: 15,
    name: "Mira",
    image: "../assets/images/mira.png",
    icon: "../assets/icons/mira-icon.png",
    active: true,
  },
  {
    id: 16,
    name: "Lesion",
    image: "../assets/images/lesion.png",
    icon: "../assets/icons/lesion-icon.png",
    active: true,
  },
  {
    id: 17,
    name: "Ela",
    image: "../assets/images/ela.png",
    icon: "../assets/icons/ela-icon.png",
    active: true,
  },
  {
    id: 18,
    name: "Vigil",
    image: "../assets/images/vigil.png",
    icon: "../assets/icons/vigil-icon.png",
    active: true,
  },
  {
    id: 19,
    name: "Maestro",
    image: "../assets/images/maestro.png",
    icon: "../assets/icons/maestro-icon.png",
    active: true,
  },
  {
    id: 20,
    name: "Alibi",
    image: "../assets/images/alibi.png",
    icon: "../assets/icons/alibi-icon.png",
    active: true,
  },
  {
    id: 21,
    name: "Clash",
    image: "../assets/images/clash.png",
    icon: "../assets/icons/clash-icon.png",
    active: true,
  },
  {
    id: 22,
    name: "Kaid",
    image: "../assets/images/kaid.png",
    icon: "../assets/icons/kaid-icon.png",
    active: true,
  },
  {
    id: 23,
    name: "Mozzie",
    image: "../assets/images/mozzie.png",
    icon: "../assets/icons/mozzie-icon.png",
    active: true,
  },
  {
    id: 24,
    name: "Warden",
    image: "../assets/images/warden.png",
    icon: "../assets/icons/warden-icon.png",
    active: true,
  },
  {
    id: 25,
    name: "Goyo",
    image: "../assets/images/goyo.png",
    icon: "../assets/icons/goyo-icon.png",
    active: true,
  },
  {
    id: 26,
    name: "Wamai",
    image: "../assets/images/wamai.png",
    icon: "../assets/icons/wamai-icon.png",
    active: true,
  },
  {
    id: 27,
    name: "Oryx",
    image: "../assets/images/oryx.png",
    icon: "../assets/icons/oryx-icon.png",
    active: true,
  },
  {
    id: 28,
    name: "Melusi",
    image: "../assets/images/melusi.png",
    icon: "../assets/icons/melusi-icon.png",
    active: true,
  },
  {
    id: 29,
    name: "Aruni",
    image: "../assets/images/aruni.png",
    icon: "../assets/icons/aruni-icon.png",
    active: true,
  },
  {
    id: 30,
    name: "Thunderbird",
    image: "../assets/images/thunderbird.png",
    icon: "../assets/icons/thunderbird-icon.png",
    active: true,
  },
  {
    id: 31,
    name: "Thorn",
    image: "../assets/images/thorn.png",
    icon: "../assets/icons/thorn-icon.png",
    active: true,
  },
  {
    id: 32,
    name: "Azami",
    image: "../assets/images/azami.png",
    icon: "../assets/icons/azami-icon.png",
    active: true,
  },
  {
    id: 33,
    name: "Solis",
    image: "../assets/images/solis.png",
    icon: "../assets/icons/solis-icon.png",
    active: true,
  },
  {
    id: 35,
    name: "Fenrir",
    image: "../assets/images/fenrir.png",
    icon: "../assets/icons/fenrir-icon.png",
    active: true,
  },
  {
    id: 35,
    name: "Tubarão",
    image: "../assets/images/tubarão.png",
    icon: "../assets/icons/tubarão-icon.png",
    active: true,
  }
];
